// This file is "model.dart"
import 'package:bayyinah_rana/models/ayah_data_model.dart';
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'ayah_model.mapper.dart';

@MappableClass()
class AyahModel with AyahModelMappable {
  final int code;
  final String status;
  final AyahDataModel data;

  AyahModel(this.code, this.status, this.data);
}
