// This file is "model.dart"
import 'package:bayyinah_rana/models/surah_model.dart';
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'ayah_data_model.mapper.dart';

@MappableClass()
class AyahDataModel with AyahDataModelMappable {
  final int numberInSurah;
  final String text;
  final SurahModel surah;

  AyahDataModel(this.numberInSurah, this.text, this.surah);
}
