// This file is "model.dart"
import 'package:bayyinah_rana/models/ayah_data_model.dart';
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'surah_model.mapper.dart';

@MappableClass()
class SurahModel with SurahModelMappable {
  final String name;
  SurahModel({ required this.name});
}
